manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk_locals_base
      url-base: https://github.com/ander-zz
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-locales
      remote: zmk_locals_base
      revision: main
      import: west.yml
  self:
    path: config
